# NeuralBlitz v50 Grafana Datasource Configuration

apiVersion: 1

datasources:
  - name: NeuralBlitz Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s
      httpMethod: GET
    secureJsonData:
      # Add API key here if needed
